#!/bin/sh

[ -z "$1" ] && echo missing branch or tag >&2 && exit 1

cd .. && git archive -o docker/coog-paybox-callback.tar.gz "$1"
# (cd .. && tar -czvf docker/coog-paybox-callback.tar.gz \
#     config.js \
#     index.js \
#     package.json)

mkdir docker/coog-paybox-callback && \
    tar -xf docker/coog-paybox-callback.tar.gz -C docker/coog-paybox-callback && \
    docker build -t "coog/paybox-callback:$1" .

rm -rf coog-paybox-callback*
